title: π’» Portfolio

description: "
<br>λ°κ°‘μµλ‹λ‹¤. π‘‹π» <br>
μ‹¤μ „μ— κ°•ν• κ°λ°μ λ°•μ£Όν•μ <br>
ν¬νΈν΄λ¦¬μ¤ μλ£μ…λ‹λ‹¤. <br><br>

<strong>Email.</strong>  pjh9447@gmail.com <br>
<strong>Phone.</strong>  010-5115-2980"

logo: /assets/img/my-official-photo.png

show_downloads: false

# google_analytics: UA-12345678-9

theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
